ok this didn‘t work out, do it properly

diff --git a/src/share/misc/bsdstats b/src/share/misc/bsdstats
--- a/src/share/misc/bsdstats
+++ b/src/share/misc/bsdstats
@@ -1,4 +1,4 @@
-# $MirOS: src/share/misc/bsdstats,v 1.57 2007/09/28 01:59:46 tg Exp $
+# $MirOS: src/share/misc/bsdstats,v 1.58 2007/09/28 11:26:47 tg Exp $
 # $FreeBSD: ports/sysutils/bsdstats/files/300.statistics,v 1.38 2006/12/05 13:49:45 scrappy Exp $
 #-
 # Copyright (c) 2007
@@ -92,7 +92,7 @@ function uri_escape {
 	'
 }
 
-rcsid_code='$MirOS: src/share/misc/bsdstats,v 1.57 2007/09/28 01:59:46 tg Exp $'
+rcsid_code='$MirOS: srx/share/misc/bsdstats,v 1.58 2007/09/28 11:26:47 tg Exp $'
 uname_code=$(uri_escape "$(uname -a | tr -d '\012\015')$stats_sysadd$ac")
 
 if [[ $(uname -M 2>&1) = *MirBSD* ]]; then
@@ -402,9 +402,12 @@ if (( now > (stats_report_time + 10 * 86400) )); then
 		qs=
 		# scan for FreeBSD Ports, MirPorts, OpenBSD Ports, pkgsrc
 		for dir in /{,{*/,.*/}{,{*/,.*/}{,{*/,.*/}}}}{db/pkg,pkgdb}; do
-			[[ -e $dir/+CONTENTS ]] || continue
+			[[ -e $dir ]] || continue
 			for file in $dir/*/+CONTENTS; do
-				if [[ -e ${file%CONTENTS}BUILD_INFO ]]; then
+				if [[ ! -s $file ]]; then
+					# silently skip
+					continue
+				elif [[ -e ${file%CONTENTS}BUILD_INFO ]]; then
 					# pkgsrc
 					doports_pkgsrc "$dir"
 				elif fgrep -qa '@comment ORIGIN' "$file"; then
