• be more flexible • use return not exit

diff --git a/src/share/misc/bsdstats b/src/share/misc/bsdstats
--- a/src/share/misc/bsdstats
+++ b/src/share/misc/bsdstats
@@ -1,4 +1,4 @@
-# $MirOS: src/share/misc/bsdstats,v 1.28 2007/05/15 01:09:10 tg Exp $
+# $MirOS: src/share/misc/bsdstats,v 1.29 2007/05/15 19:12:28 tg Exp $
 # $FreeBSD: ports/sysutils/bsdstats/files/300.statistics,v 1.38 2006/12/05 13:49:45 scrappy Exp $
 #-
 # Copyright (c) 2007
@@ -21,37 +21,76 @@
 # damage or existence of a defect, except proven that it results out
 # of said person's immediate fault when using the work as intended.
 
+#-- Configuration
+
+# server to report to
 rpt='http://rpt.bsdstats.org/scripts/'
 
+# report only known BSDs?
+do_bsdonly=1
+
+#-- Do not change below
+
 export TZ=UTC PATH=/bin:/usr/bin:/sbin:/usr/sbin
+for dir in /usr/mpkg /usr/pkg /usr/local /sw; do
+	for subdir in bin sbin; do
+		[[ -e $dir/$subdir ]] && PATH=$PATH:$dir/$subdir
+	done
+done
+
+[[ -s /var/db/bsdstats && -O /var/db/bsdstats ]] && . /var/db/bsdstats
+if [[ -e /etc/rc.conf && -O /etc/rc.conf ]]; then
+	bsdstats_flags=$(. /etc/rc.conf; echo "$bsdstats_flags")
+else
+	bsdstats_flags=YES
+fi
+
+if [[ $(uname -M 2>&1) = *MirBSD* ]]; then
+	opsys=MirBSD
+	ops_m=1
+else
+	opsys=$(uname -s)
+	ops_m=0
+fi
+if [[ $do_bsdonly != 0 && $opsys != @(*BSD|DragonFly) ]]; then
+	print -u2 Error: $opsys is not a BSD!
+	return 1
+fi
 
 if [[ -x /usr/bin/ftp ]]; then
 	fetch='/usr/bin/ftp -Vo -'
-elif [[ -x /usr/bin/wget ]]; then
-	fetch='/usr/bin/wget -qO -'
+elif whence -p wget >&- 2>&-; then
+	fetch="$(whence -p wget) -qO -"
+elif whence -p ftp >&- 2>&-; then
+	fetch="$(whence -p ftp) -Vo -"
 else
 	print -u2 Error: select a HTTP fetch programme!
-	exit 1
+	return 1
 fi
 
 if date --help >/dev/null 2>&1; then
-	datetype=gnu
+	function timet2date {
+		date -d @$*
+	}
 else
+	function timet2date {
+		date -r $*
+	}
 	datetype=bsd
 fi
 
-function timet2date
-{
-	if [[ $datetype = gnu ]]; then
-		date -d @$*
-	else
-		date -r $*
-	fi
-}
+if whence -p logger >&- 2>&-; then
+	function logit {
+		print -nr -- "$@" | logger -t bsdstats
+	}
+else
+	function logit {
+		print -r bsdstats: "$@"
+	}
+fi
 
 # RFC 2396
-function uri_escape
-{
+function uri_escape {
 	print -nr -- "$*" | sed -e '
 	    s.%.%25.g
 	    s.;.%3B.g
@@ -82,8 +121,7 @@ function uri_escape
 }
 
 # weird POST reporting of ports in $qs
-function report_ports
-{
+function report_ports {
 	#XXX honour http_proxy host/port
 	host=${rpt#http://}
 	host=${host%%/*}
@@ -101,7 +139,7 @@ function report_ports
 	qs="token=$stats_key&key=$stats_token$qs"
 	qs="POST $path HTTP/1.0
 Host: $host
-User-Agent: bsdstats \$MirOS: src/share/misc/bsdstats,v 1.28 2007/05/15 01:09:10 tg Exp $
+User-Agent: bsdstats \$MirOS: src/share/misc/bsdstats,v 1.29 2007/05/15 19:12:28 tg Exp $
 Connection: close
 Content-Type: application/x-www-form-urlencoded
 Content-Length: ${#qs}
@@ -109,15 +147,16 @@ Content-Length: ${#qs}
 $qs"
 	res=$(sleep $((RANDOM % 99 + 21)); \
 	    print -r -- "$qs" | nc $host $port 2>/dev/null)
-	print -r "ports report to $host:$port with '$qs' -> ${res:-ERROR}" | \
-	    logger -t bsdstats
+	logit "ports report to $host:$port with '$qs' -> ${res:-ERROR}"
 	[[ $res = *OK* ]] || ok=0
 }
 
 host=${rpt#http://}
 host=${host%%/*}
 # do it twice in case DNS is slow
-[[ -x /usr/bin/host ]] && if [[ $host = *bsdstats.org ]]; then
+if ! whence -p host >&- 2>&-; then
+	print warning: cannot do DNS checks
+elif [[ $host = *bsdstats.org ]]; then
 	res=$(host -t txt bsdstats.org. & dnspid=$!; \
 	    (sleep 12; kill $dnspid) >&- 2>&- & wait $dnspid)
 	[[ $res = *@(not\ found)* || $res = *NXDOMAIN* ]] && res=
@@ -140,13 +179,20 @@ else
 		return 0
 	fi
 fi
+
+if print test | uuencode -m - >/dev/null 2>&1; then
+	uname_code=ok:$(uname -a | uuencode -m - | tr -d '\012\015 ')
+else
+	print warning: uuencode missing or incomplete
+	uname_code=not:$RANDOM$(date +%s)
+fi
+uname_code=$uname_code$stats_sysadd
+
 stats_token=
 integer stats_token_time=0
 integer stats_report_time=0
-[[ -s /var/db/bsdstats ]] && . /var/db/bsdstats
-print "last report time was: $stats_report_time ($(timet2date $stats_report_time))"
-bsdstats_flags=$(. /etc/rc.conf; echo "$bsdstats_flags")
-uname_code=$(uname -a | uuencode -m - | tr -d '\012\015 ')$stats_sysadd
+print "last report time was: $stats_report_time" \
+    "($(timet2date $stats_report_time))"
 (( stats_report_time < 1136073623 )) && stats_report_time=0
 [[ $stats_uname_code = $uname_code ]] || stats_report_time=0
 (( stats_token_time < 1136073623 )) && stats_token_time=0
@@ -154,31 +200,30 @@ uname_code=$(uname -a | uuencode -m - | tr -d '\012\015 ')$stats_sysadd
 integer ok=1
 if [[ -z $stats_token || -z $stats_key ]]; then
 	stats_report_time=0
+	if ! whence -p openssl >&- 2>&-; then
+		print -u2 Error: openssl tool missing
+		return 1
+	fi
 	stats_key=$(uri_escape $(openssl rand -base64 32))
 	uri="getid.php?key=$stats_key"
 	res=$(sleep $((RANDOM % 99 + 21)); \
 	    $fetch "$rpt$uri" 2>/dev/null)
-	print -r "firstrun $uri -> ${res:-ERROR}" | logger -t bsdstats
+	logit "firstrun $uri -> ${res:-ERROR}"
 	stats_token=$(uri_escape $(eval $res; print -nr -- "$KEY"))
 	stats_token_time=$(date +%s)
 fi
 integer now=$(date +%s)
 let now-=86400	# account for time zone differences
 if (( $(timet2date $stats_report_time +%Y%m) < $(timet2date $now +%Y%m) )); then
-	opsys=$(uname -s)
-	uname -M 2>&1 | fgrep MirBSD >/dev/null 2>&1 && opsys=MirBSD
 	version=$(uname -r)
-	[[ -n $stats_sysadd ]] && version=$version$stats_sysadd
 	arch=$(uname -m)
 	if [[ $opsys = GNU* ]]; then
 		arch=$(uname -p)
 		[[ -z $stats_sysadd && -s /etc/debian_version ]] && \
-		    version=$version.Debian-$(tr / _ </etc/debian_version)
-	elif [[ $opsys = MirBSD && -n $stats_sysadd ]]; then
-		uname -M 2>&1 | fgrep MirBSD >/dev/null 2>&1 && \
-		    version=$(uname -M | sed 's/^.*BSD #\([0-9]\).*/\1/' \
-		    )$stats_sysadd
-	elif [[ $opsys = MirBSD ]]; then
+		    stats_sysadd=.Debian-$(tr / _ </etc/debian_version)
+	elif [[ $ops_m = 1 && -n $stats_sysadd ]]; then
+		version=$(uname -M | sed 's/^.*BSD #\([0-9]\).*/\1/')
+	elif [[ $opsys = MirBSD && -z $stats_sysadd ]]; then
 		version=$(uname -l)
 		version=${version#\#}
 		version=${version%%-*}
@@ -200,30 +245,33 @@ if (( $(timet2date $stats_report_time +%Y%m) < $(timet2date $now +%Y%m) )); then
 			(132)	version=${version}ter ;;
 			(134)	version=${version}quater ;;
 			(136)	version=${version}quinquies ;;
-			(*)	version=${version}num.$((pl/2-63))ies ;;
+			(*)	version=${version}num.$(( pl / 2 - 63 ))ies ;;
 			}
 		fi
 	fi
 	uri="enable_token.php?key=$stats_key&token=$stats_token"
-	res=$(sleep $((RANDOM % 99 + 21)); \
-	    $fetch "$rpt$uri" 2>/dev/null)
-	print -r "init $uri -> ${res:-ERROR}" | logger -t bsdstats
-	uri="report_system.php?token=$stats_key&key=$stats_token&rel=$(uri_escape $version)&arch=$arch&opsys=$opsys"
-	res=$(sleep $((RANDOM % 99 + 21)); \
-	    $fetch "$rpt$uri" 2>/dev/null)
-	print -r "system report $uri -> ${res:-ERROR}" | logger -t bsdstats
+	res=$(sleep $((RANDOM % 99 + 21)); $fetch "$rpt$uri" 2>/dev/null)
+	logit "init $uri -> ${res:-ERROR}"
+	uri="report_system.php?token=$stats_key&key=$stats_token"
+	uri="$uri&rel=$(uri_escape $version$stats_sysadd)"
+	uri="$uri&arch=$arch&opsys=$opsys"
+	res=$(sleep $((RANDOM % 99 + 21)); $fetch "$rpt$uri" 2>/dev/null)
+	logit "system report $uri -> ${res:-ERROR}"
 	[[ $res = *OK* ]] || ok=0
 	if [[ $bsdstats_flags = YES ]]; then
-		cpu=$(sysctl -n hw.model)
+		# Hardware report: CPU(s)
 		integer ncpus=$(sysctl -n hw.ncpu)
+		cpu=$(sysctl -n hw.model)
 		(( ncpus < 2 )) && let ncpus=1
-		uri="report_cpu.php?token=$stats_key&key=$stats_token&cpus=$ncpus&vendor=$(print -r -- "$cpu" | cut -d' ' -f1)&cpu_type=$(uri_escape $(print -r -- "$cpu" | cut -d' ' -f2-))"
-		res=$(sleep $((RANDOM % 99 + 21)); \
-		    $fetch "$rpt$uri" 2>/dev/null)
-		print -r "cpu report $uri -> ${res:-ERROR}" | logger -t bsdstats
+		uri="report_cpu.php?token=$stats_key&key=$stats_token"
+		uri="$uri&cpus=$ncpus&vendor=${cpu%% *}"
+		uri="$uri&cpu_type=$(uri_escape "${cpu#* }")"
+		res=$(sleep $((RANDOM % 99 + 21)); $fetch "$rpt$uri" 2>/dev/null)
+		logit "cpu report $uri -> ${res:-ERROR}"
 		[[ $res = *OK* ]] || ok=0
-		# report MirPorts Framework installed binary packages
+		# Software report
 		qs=
+		# report MirPorts Framework installed binary packages
 		(find /usr/mpkg/db/pkg -name +CONTENTS -print0 2>/dev/null | \
 		    xargs -0 grep '^@comment.*subdir=' | \
 		    sed 's!^[^:]*/\([^/:]*\)/+CONTENTS:.*subdir=\([^, ]*\).*$!\1:\2!' | \
@@ -266,15 +314,16 @@ if (( $(timet2date $stats_report_time +%Y%m) < $(timet2date $now +%Y%m) )); then
 			done
 			qs="$qs:$(uri_escape "$name")"
 		done
-		# report any found binary packages now at once
+		# send info about any found binary packages now at once
 		[[ -z $qs ]] || report_ports
 	fi
 	uri="disable_token.php?key=$stats_key&token=$stats_token"
-	res=$(sleep $((RANDOM % 99 + 21)); \
-	    $fetch "$rpt$uri" 2>/dev/null)
-	print -r "done $uri -> ${res:-ERROR}" | logger -t bsdstats
-	(( ok )) && stats_report_time=$(date +%s)
-	(( ok )) && print "Reported successfully on $(date)"
+	res=$(sleep $((RANDOM % 99 + 21)); $fetch "$rpt$uri" 2>/dev/null)
+	logit "done $uri -> ${res:-ERROR}"
+	if (( ok )); then
+		stats_report_time=$(date +%s)
+		print "Reported successfully on $(date)"
+	fi
 else
 	print "Nothing to do for now..."
 fi
@@ -286,4 +335,6 @@ print "stats_report_time=$stats_report_time" >>/var/db/bsdstats.new
 print "stats_uname_code=$uname_code" >>/var/db/bsdstats.new
 mv -f /var/db/bsdstats.new /var/db/bsdstats
 (( ok )) || print some failures occured, check /var/log/messages, tag bsdstats
-print "done, used token from $stats_token_time ($(timet2date $stats_token_time))"
+print "done, used token from $stats_token_time" \
+    "($(timet2date $stats_token_time))"
+return 0
