• check if we're really run with mksh • fix my unportability in the pkgsrc case, tested on DragonFly by TGEN • fix fbsd-style device reporting, tested on DragonFly by TGEN • fix a missing URI part in a logger call • fix a stupid syntax error • fix a thinko preventing pkgsrc scans from running, tested on MirOS
Thanks to TGEN (Thomas E. Spanjaard) for testing despite disliking bsdstats

diff --git a/src/share/misc/bsdstats b/src/share/misc/bsdstats
--- a/src/share/misc/bsdstats
+++ b/src/share/misc/bsdstats
@@ -1,4 +1,4 @@
-# $MirOS: src/share/misc/bsdstats,v 1.41 2007/05/18 07:31:24 tg Exp $
+# $MirOS: src/share/misc/bsdstats,v 1.42 2007/05/19 19:11:44 tg Exp $
 # $FreeBSD: ports/sysutils/bsdstats/files/300.statistics,v 1.38 2006/12/05 13:49:45 scrappy Exp $
 #-
 # Copyright (c) 2007
@@ -31,6 +31,14 @@ do_bsdonly=1
 
 #-- Do not change below
 
+case $KSH_VERSION in
+*MIRBSD\ KSH*) ;;
+*)
+	echo "ERROR: run $0 with the MirBSD Korn Shell (mksh)!"
+	echo >&2 "Fatal: '$0' was not run from mksh, aborting."
+	return 1 ;;
+esac
+
 stats_token=
 integer stats_token_time=0
 integer stats_report_time=0
@@ -49,7 +57,7 @@ for dir in /usr/mpkg /usr/pkg /usr/local /sw; do
 	done
 done
 
-rcsid_code='$MirOS: src/share/misc/bsdstats,v 1.41 2007/05/18 07:31:24 tg Exp $'
+rcsid_code='$MirOS: src/share/misc/bsdstats,v 1.42 2007/05/19 19:11:44 tg Exp $'
 
 if [[ $(uname -M 2>&1) = *MirBSD* ]]; then
 	opsys=MirBSD
@@ -150,7 +158,7 @@ function report_ports {
 	qs="token=$stats_key&key=$stats_token$qs"
 	qs="POST $path HTTP/1.0
 Host: $host
-User-Agent: bsdstats \$MirOS: src/share/misc/bsdstats,v 1.41 2007/05/18 07:31:24 tg Exp $
+User-Agent: bsdstats \$MirOS: src/share/misc/bsdstats,v 1.42 2007/05/19 19:11:44 tg Exp $
 Connection: close
 Content-Type: application/x-www-form-urlencoded
 Content-Length: ${#qs}
@@ -177,8 +185,8 @@ function doports_pkgsrc {
 		name=${fn%/*}		# directory
 		name=${name##*/}	# pkgname
 		[[ $name = *@(nb)+([0-9]) ]] || name=${name}nb0
-		eval $(print 'all:\n\t@print -r -- "dir=${PKGPATH:Q}' \
-		    'flavours=${PKG_OPTIONS:Q}"\n.include "'"$fn\"" | \
+		eval $(print 'all:\n\t@printf "dir=%s flavours=%s"' \
+		    '${PKGPATH:Q:Q} ${PKG_OPTIONS:Q:Q}\n.include' "\"$fn\"" | \
 		    $bmake -f - all)	# subdir, flavours
 		qs="$qs&port[]=$(uri_escape "${dir%%/*}")"
 		for flavour in $flavours; do
@@ -232,13 +240,10 @@ function doports_openmir {
 
 function dodevs_fbsd {
 	# taken from scrappy's script, neither optimised nor tested
-	for line in $(/usr/sbin/pciconf -l); do
-		qs="$qs&dev[]=$(uri_escape "$(echo "$line" | \
-		    awk -F\@ '{print $1}')")"
-		qs="$qs:$(uri_escape "$(echo "$line" | \
-		    awk '{print $4}' | cut -c8-15)")"
-		qs="$qs:$(uri_escape "$(echo "$line" | \
-		    awk '{print $2}' | cut -c9-14)")"
+	/usr/sbin/pciconf -l |&
+	while IFS='@ =	' read -pr driver x1 x2 class x4 x5 x6 chip rest; do
+		qs="$qs&dev[]=$(uri_escape "$driver")"
+		qs="$qs:$(uri_escape "${chip#0x}"):$(uri_escape "${class#0x}")"
 	done
 }
 
@@ -366,16 +371,16 @@ if (( now > (stats_report_time + 10 * 86400) )); then
 		if [[ -n $qs ]]; then
 			res=$(sleep $((RANDOM % 99 + 21)); \
 			    $fetch "$rpt$uri$qs" 2>/dev/null)
-			logit "devices report $uri -> ${res:-ERROR}"
+			logit "devices report $uri$qs -> ${res:-ERROR}"
 			[[ $res = *OK* ]] || ok=0
 		fi
 		# Software report
 		qs=
 		# scan for FreeBSD Ports, MirPorts, OpenBSD Ports, pkgsrc
 		for dir in /{,usr/,opt/}*/{db/pkg,pkgdb}; do
-			[[ -e $dir || continue ]]
+			[[ -e $dir ]] || continue
 			for file in $dir/*/+CONTENTS; do
-				if [[ -e ${dir%CONTENTS}BUILD_INFO ]]; then
+				if [[ -e ${file%CONTENTS}BUILD_INFO ]]; then
 					# pkgsrc
 					doports_pkgsrc "$dir"
 				elif fgrep -q '@comment ORIGIN' "$file"; then
