simplify further: * make use of $PATH * case foo in a) -> case foo { (a) * case -> if, when possible * >/dev/null -> >&- (idea from freewrt)
some of that code deserves more polishing though

diff --git a/src/etc/rc b/src/etc/rc
--- a/src/etc/rc
+++ b/src/etc/rc
@@ -1,4 +1,4 @@
-# $MirOS: src/etc/rc,v 1.26 2006/08/09 12:46:50 tg Exp $
+# $MirOS: src/etc/rc,v 1.27 2006/08/09 13:31:38 tg Exp $
 # $OpenBSD: rc,v 1.277 2006/01/12 21:54:15 deraadt Exp $
 #-
 # System startup script run by init on autoboot or after single-user.
@@ -6,11 +6,12 @@
 # is the controlling terminal. This is called with _PATH_BSHELL.
 
 case $KSH_VERSION in
-*MIRBSD?KSH*) ;;
+*MIRBSD?KSH*)	;;
 *)	for x in /bin/mksh /bin/ksh; do
 		case $($x -c 'echo $KSH_VERSION') in
 		*MIRBSD?KSH*)
-			exec $x "$0" "$@" ;;
+			exec $x "$0" "$@"
+			;;
 		esac
 	done
 	/bin/echo "$0: FATAL: need a mirbsd korn shell!" >&2
@@ -42,18 +43,17 @@ update_limit() {
 	local _new _suf
 
 	for _suf in "" -cur -max; do
-		_new=$(getcap -f /etc/login.conf -s $_lc$_suf \
-		    daemon 2>/dev/null)
+		_new=$(getcap -f /etc/login.conf -s $_lc$_suf daemon 2>&-)
 		if [[ -n $_new ]]; then
 			[[ $_new = infinity ]] && _new=unlimited
 			case $_suf {
-			-cur)
+			(-cur)
 				ulimit -S $_fl $_new
 				;;
-			-max)
+			(-max)
 				ulimit -H $_fl $_new
 				;;
-			*)
+			(*)
 				ulimit $_fl $_new
 				return
 				;;
@@ -67,14 +67,14 @@ sysctl_conf() {
 
 	# delete comments and blank lines
 	set -- $(stripcom /etc/sysctl.conf)
-	while [ $# -ge 1 ] ; do
+	while [ $# -ge 1 ]; do
 		sysctl $1
 		# update limits if needed
 		case $1 {
-		kern.maxproc=*)
+		(kern.maxproc=*)
 			update_limit -p maxproc
 			;;
-		kern.maxfiles=*)
+		(kern.maxfiles=*)
 			update_limit -n openfiles
 			;;
 		}
@@ -88,8 +88,8 @@ mixerctl_conf()
 
 	# delete comments and blank lines
 	set -- $(stripcom /etc/mixerctl.conf)
-	while [ $# -ge 1 ] ; do
-		mixerctl -q $1 >/dev/null 2>&1
+	while [ $# -ge 1 ]; do
+		mixerctl -q $1 >&- 2>&-
 		shift
 	done
 }
@@ -104,8 +104,8 @@ wsconsctl_conf()
 "
 	set -- $(stripcom /etc/wsconsctl.conf)
 	IFS=$save_IFS
-	while [ $# -ge 1 ] ; do
-		eval /sbin/wsconsctl -w $1
+	while [ $# -ge 1 ]; do
+		eval wsconsctl -w $1
 		shift
 	done
 }
@@ -169,9 +169,9 @@ export PATH=/sbin:/bin:/usr/sbin:/usr/bin
 
 if [[ $1 = shutdown ]]; then
 	echo Received shutdown request.
-	dd if=/dev/urandom of=/var/db/host.random bs=1024 count=8 \
-	    >/dev/null 2>&1 && chmod 600 /var/db/host.random \
-	    >/dev/null 2>&1 && if [[ -f /etc/rc.shutdown ]]; then
+	dd if=/dev/urandom of=/var/db/host.random bs=1024 count=8 >&- 2>&- && \
+	    chmod 600 /var/db/host.random >&- 2>&- && \
+	    if [[ -f /etc/rc.shutdown ]]; then
 		echo /etc/rc.shutdown in progress...
 		. /etc/rc.shutdown
 		echo /etc/rc.shutdown complete.
@@ -182,7 +182,7 @@ if [[ $1 = shutdown ]]; then
 			if=${hn#/etc/hostname.}
 			test "$if" = "carp[0-9]*" && continue
 
-			ifconfig $if >/dev/null 2>&1 && ifconfig $if down
+			ifconfig $if >&- 2>&- && ifconfig $if down
 		done
 
 		[[ $powerdown = YES ]] && exit 2
@@ -240,18 +240,13 @@ if [[ -n $softdrives_ide ]]; then
 	_flags=""
 	set -o noglob
 	for drv in $softdrives_ide; do
-		case $_flags {
-		*$drv*)
-			;;	# Already done
-		*)
+		if [[ $_flags != *$drv* ]]; then
 			echo -n " $drv"
-			/sbin/atactl /dev/r${drv}c secfreeze \
-			    >/dev/null 2>&1
-			/sbin/atactl /dev/r${drv}c writecachedisable \
-			    >/dev/null 2>&1 || echo -n !
+			atactl /dev/r${drv}c secfreeze >&- 2>&-
+			atactl /dev/r${drv}c writecachedisable >&- 2>&- || \
+			    echo -n !
 			_flags="$_flags $drv"
-			;;
-		}
+		fi
 	done
 	set +o noglob
 	echo .
@@ -264,30 +259,30 @@ elif [[ $1 = autoboot ]]; then
 	echo Automatic boot in progress: starting file system checks.
 	fsck -p
 	case $? {
-	0)
+	(0)
 		;;
-	2)
+	(2)
 		exit 1
 		;;
-	4)
+	(4)
 		echo Rebooting...
 		reboot
 		echo "Reboot failed; help!"
 		exit 1
 		;;
-	8)
+	(8)
 		echo "Automatic file system check failed; help!"
 		exit 1
 		;;
-	12)
+	(12)
 		echo Boot interrupted.
 		exit 1
 		;;
-	130)
+	(130)
 		# interrupt before catcher installed
 		exit 1
 		;;
-	*)
+	(*)
 		echo "Unknown error; help!"
 		exit 1
 		;;
@@ -296,59 +291,42 @@ fi
 
 trap "echo Boot interrupted.; exit 1" 3
 
-umount -a >/dev/null 2>&1
+umount -a >&- 2>&-
 let i=0
 while (( i < _fstab )); do
 	if [[ ${_mp[i]} = / && ${_opt[i]} != ro* ]]; then
-		mount -uwo "${_opt[i]}" "${_dev[i]}" / >/dev/null 2>&1
-		if [[ $? -ne 0 ]]; then
-			case ${_opt[i]} {
-			*softdep*)	;;
-			*)	echo -n 'WARNING: Your root filesystem failed'
+		if ! mount -uwo "${_opt[i]}" "${_dev[i]}" / >&- 2>&-; then
+			if [[ ${_opt[i]} != *softdep* ]]; then
+				echo -n 'WARNING: Your root filesystem failed'
 				echo -n ' to remount read-write! <forcing...>'
 				echo 'The system is probably severely damaged'
-				;;
-			}
+			fi
 			mount -ufwo "${_opt[i]}" "${_dev[i]}" /
 		fi
-	else
-		case ${_opt[i]} {
-		*noauto*)
-			;;
-		sw*)
-			;;	# Swap
-		xx*)
-			;;	# ignore totally
-		*)
-			if [[ ${_fstype[i]} = ffs ]]; then
-				mount -t ffs -o "${_opt[i]}" "${_dev[i]}" \
-					"${_mp[i]}" >/dev/null 2>&1
-				if [[ $? -ne 0 ]]; then
-					case ${_opt[i]} {
-					*softdep*)	;;
-					*)	echo -n "Warning: force-mounti"
-						echo -n "ng unchecked ffs file"
-						echo -n "system: ${_dev[i]}"
-						echo " -> ${_mp[i]}  nosoftdep"
-						;;
-					}
-					mount -f -t ffs -o "${_opt[i]}" \
-					    "${_dev[i]}" "${_mp[i]}"
+	elif [[ ${_opt[i]} != *noauto* && ${_opt[i]} != @(sw|xx)* ]]; then
+		if [[ ${_fstype[i]} = ffs ]]; then
+			if ! mount -t ffs -o "${_opt[i]}" "${_dev[i]}" \
+				"${_mp[i]}" >&- 2>&-; then
+				if [[ ${_opt[i]} != *softdep* ]]; then
+					echo -n "Warning: force-mounti"
+					echo -n "ng unchecked ffs file"
+					echo -n "system: ${_dev[i]}"
+					echo " -> ${_mp[i]}  nosoftdep"
 				fi
-			elif [[ ${_fstype[i]} = nfs ]]; then
-				: # Ignore NFS this early in the boot process
-			else
-				mount -t "${_fstype[i]}" -o "${_opt[i]}" \
+				mount -f -t ffs -o "${_opt[i]}" \
 				    "${_dev[i]}" "${_mp[i]}"
 			fi
-			;;
-		}
+		elif [[ ${_fstype[i]} != nfs ]]; then
+			# Ignore NFS this early in the boot process
+			mount -t "${_fstype[i]}" -o "${_opt[i]}" \
+			    "${_dev[i]}" "${_mp[i]}"
+		fi
 	fi
 	let i++
 done
 mount -a -t nonfs
 # root on nfs may require this
-_flags=$(mount 2>/dev/null | fgrep ' on / ' 2>/dev/null)
+_flags=$(mount 2>&- | fgrep ' on / ' 2>&-)
 [[ -z $_flags || $_flags = *\(*read-only* ]] && mount -uw /
 # root is now writable
 rm -f /fastboot
@@ -363,21 +341,19 @@ if [[ $pf != NO ]]; then
 	RULES="$RULES\npass in proto tcp from any to any port 22 keep state"
 	RULES="$RULES\npass out proto { tcp, udp } from any to any port 53 keep state"
 	RULES="$RULES\npass out inet proto icmp all icmp-type echoreq keep state"
-	if ifconfig lo0 inet6 >/dev/null 2>&1; then
+	if ifconfig lo0 inet6 >&- 2>&-; then
 		RULES="$RULES\npass out inet6 proto icmp6 all icmp6-type neighbrsol"
 		RULES="$RULES\npass in inet6 proto icmp6 all icmp6-type neighbradv"
 		RULES="$RULES\npass out inet6 proto icmp6 all icmp6-type routersol"
 		RULES="$RULES\npass in inet6 proto icmp6 all icmp6-type routeradv"
 	fi
 	RULES="$RULES\npass proto { pfsync, carp }"
-	case $(sysctl vfs.mounts.nfs 2>/dev/null) in
-	*[1-9]*)
+	if [[ "$(sysctl vfs.mounts.nfs 2>&-)" = *[1-9]* ]]; then
 		# don't kill NFS
 		RULES="scrub in all no-df\n$RULES"
 		RULES="$RULES\npass in proto udp from any port { 111, 2049 } to any"
 		RULES="$RULES\npass out proto udp from any to any port { 111, 2049 }"
-		;;
-	esac
+	fi
 	echo $RULES | pfctl -f -
 	pfctl -e
 fi
@@ -399,7 +375,7 @@ fi
 # load arp tables
 if [[ $arptables = YES && -s /etc/arp.conf ]]; then
 	echo Setting static ARP table entries
-	/usr/sbin/arp -f /etc/arp.conf
+	arp -f /etc/arp.conf
 fi
 
 [[ $pf != NO && -s $pf_rules ]] && pfctl -f "$pf_rules"
@@ -408,8 +384,8 @@ fi
 let i=0
 while (( i < _fstab )); do
 	if [[ ${_mp[i]} = /@(usr|var) ]]; then
-		_flags=$(mount 2>/dev/null | fgrep " on ${_mp[i]} " 2>/dev/null)
-		[[ -z $_flags ]] && mount ${_mp[i]} >/dev/null 2>&1
+		_flags=$(mount 2>&- | fgrep " on ${_mp[i]} " 2>&-)
+		[[ -z $_flags ]] && mount ${_mp[i]} >&- 2>&-
 	fi
 	let i++
 done
@@ -418,9 +394,8 @@ done
 # one through /dev/urandom; else reset seed file anyway so that
 # if a shutdown-less reboot occurs the next seed is not a repeat
 cat /var/db/host.random >/dev/arandom 2>&1
-dd if=/dev/urandom of=/var/db/host.random bs=1024 count=8 \
-    >/dev/null 2>&1
-chmod 600 /var/db/host.random >/dev/null 2>&1
+dd if=/dev/urandom of=/var/db/host.random bs=1024 count=8 >&- 2>&-
+chmod 600 /var/db/host.random >&- 2>&-
 
 # clean up left-over files
 rm -f /etc/nologin
@@ -441,8 +416,7 @@ if [[ -d /var/empty ]]; then
 fi
 syslogd $syslogd_flags
 
-[[ $pf != NO && $pflogd_flags != NO ]] && if ifconfig pflog0 \
-    >/dev/null 2>&1; then
+[[ $pf != NO && $pflogd_flags != NO ]] && if ifconfig pflog0 >&- 2>&-; then
 	ifconfig pflog0 up
 	pflogd $pflogd_flags
 fi
@@ -526,7 +500,7 @@ chown root:wheel /dev/tty[pqrstuvwxyzPQRST]*
     'password file may be incorrect -- /etc/ptmp exists'
 
 echo clearing /tmp
-_flags=$(mount 2>/dev/null | fgrep " on /tmp" 2>/dev/null)
+_flags=$(mount 2>&- | fgrep " on /tmp" 2>&-)
 if [[ -z $_flags ]]; then
 	# clean up as usual on small systems
 	rm -rf /tmp
@@ -606,10 +580,9 @@ if [[ ! -f /etc/ssl/private/default.key \
 	echo -n "openssl: generating new host RSA key... "
 	rm -f /etc/ssl/{def{ault,lt-ca}.cer,private/default.key}
 	# XXX 6000-8000 is recommended... choose 4096 to be nice to old boxen
-	if /usr/sbin/openssl genrsa -out /etc/ssl/private/default.key 4096 \
-	    >/dev/null 2>&1; then
+	if openssl genrsa -out /etc/ssl/private/default.key 4096 >&- 2>&-; then
 		chmod 600 /etc/ssl/private/default.key
-		/usr/sbin/openssl req -batch -new -subj "/CN=$(hostname)/" \
+		openssl req -batch -new -subj "/CN=$(hostname)/" \
 		    -key /etc/ssl/private/default.key \
 		    -x509 -out /etc/ssl/default.cer
 		chmod 644 /etc/ssl/default.cer
@@ -623,7 +596,7 @@ if [[ ! -f /etc/ssh/ssh_host_rsa_key ]]; then
 	echo -n "ssh-keygen: installing host RSA key... "
 	ln /etc/ssl/private/default.key /etc/ssh/ssh_host_rsa_key || \
 	    cp /etc/ssl/private/default.key /etc/ssh/ssh_host_rsa_key
-	print $(/usr/bin/ssh-keygen -yf /etc/ssh/ssh_host_rsa_key) \
+	print $(ssh-keygen -yf /etc/ssh/ssh_host_rsa_key) \
 	    $(hostname) host key >/etc/ssh/ssh_host_rsa_key.pub
 	echo done.
 fi
@@ -643,11 +616,11 @@ if [[ $mrouted_flags != NO ]]; then
 fi
 
 if [[ $ospfd_flags != NO && -x /usr/sbin/ospfd ]]; then
-	echo -n ' ospfd';		/usr/sbin/ospfd $ospfd_flags
+	echo -n ' ospfd';		ospfd $ospfd_flags
 fi
 
 if [[ $bgpd_flags != NO && -x /usr/sbin/bgpd ]]; then
-	echo -n ' bgpd';		/usr/sbin/bgpd $bgpd_flags
+	echo -n ' bgpd';		bgpd $bgpd_flags
 fi
 
 if [[ $dhcpd_flags != NO && -f /etc/dhcpd.conf ]]; then
@@ -655,24 +628,24 @@ if [[ $dhcpd_flags != NO && -f /etc/dhcpd.conf ]]; then
 	[[ -f /etc/dhcpd.interfaces ]] && \
 	    dhcpd_ifs=$(stripcom /etc/dhcpd.interfaces)
 	_flags="$dhcpd_flags $dhcpd_ifs"
-	echo -n ' dhcpd';		/usr/sbin/dhcpd $_flags
+	echo -n ' dhcpd';		dhcpd $_flags
 fi
 
-if ifconfig lo0 inet6 >/dev/null 2>&1; then
+if ifconfig lo0 inet6 >&- 2>&-; then
 	fw=$(sysctl -n net.inet6.ip6.forwarding)
 	if [[ $fw = 0 ]]; then
 		if [[ $rtsold_flags != NO ]]; then
 			echo -n ' rtsold'
-			/usr/sbin/rtsold $rtsold_flags
+			rtsold $rtsold_flags
 		fi
 	else
 		if [[ $route6d_flags != NO ]]; then
 			echo -n ' route6d'
-			/usr/sbin/route6d $route6d_flags
+			route6d $route6d_flags
 		fi
 		if [[ $rtadvd_flags != NO ]]; then
 			echo -n ' rtadvd'
-			/usr/sbin/rtadvd $rtadvd_flags
+			rtadvd $rtadvd_flags
 		fi
 	fi
 fi
@@ -693,13 +666,13 @@ fi
 # mailer other than sendmail, depending on /etc/mailer.conf.
 if [[ $sendmail_flags != NO && -s /etc/mailer.conf ]]; then
 	echo -n ' sendmail'
-	( /usr/sbin/sendmail $sendmail_flags >/dev/null 2>&1 & )
+	( /usr/sbin/sendmail $sendmail_flags >&- 2>&- & )
 fi
 
 if [[ $httpd_flags != NO ]]; then
 	# Clean up left-over httpd locks
 	rm -f /var/www/logs/{ssl_mutex,httpd.lock,accept.lock}.*
-	echo -n ' httpd';		/usr/sbin/httpd $httpd_flags
+	echo -n ' httpd';		httpd $httpd_flags
 fi
 
 if [[ $ftpd_flags != NO ]]; then
@@ -707,7 +680,7 @@ if [[ $ftpd_flags != NO ]]; then
 fi
 
 if [[ $ftpproxy_flags != NO ]]; then
-	echo -n ' ftp-proxy';		/usr/sbin/ftp-proxy $ftpproxy_flags
+	echo -n ' ftp-proxy';		ftp-proxy $ftpproxy_flags
 fi
 
 if [[ $identd_flags != NO ]]; then
@@ -751,7 +724,7 @@ if [[ $rbootd_flags != NO && -s /etc/rbootd.conf ]]; then
 fi
 
 if [[ $isdnd_flags != NO ]]; then
-	echo -n ' isdnd';		/usr/sbin/isdnd $isdnd_flags
+	echo -n ' isdnd';		isdnd $isdnd_flags
 fi
 
 echo .
@@ -763,7 +736,7 @@ mixerctl_conf
 # Only if it exists and is an unused ram disc array.
 # Compare approximately like the kernel does, except
 # we checksum the first 2 pages instead of a memcmp.
-dev=$(dd if=/dev/rrd0c count=16 2>/dev/null | cksum -a adler32)
+dev=$(dd if=/dev/rrd0c count=16 2>&- | cksum -a adler32)
 [[ $dev = 1B32098C ]] && swapctl -ap0 /dev/rd0c
 
 if [[ $sshagent_autostart != NO ]]; then
@@ -781,23 +754,23 @@ echo -n standard daemons:
 # don't run daemon if $food_flags == NO or /usr/sbin/food doesn't exist
 
 if [[ $apmd_flags != NO && -x /usr/sbin/apmd ]]; then
-	echo -n ' apmd';	/usr/sbin/apmd $apmd_flags
+	echo -n ' apmd';	apmd $apmd_flags
 fi
 
 if [[ $acpid_flags != NO && -x /usr/sbin/acpid ]]; then
-	echo -n ' acpid';	/usr/sbin/acpid $acpid_flags
+	echo -n ' acpid';	acpid $acpid_flags
 fi
 
 if [[ $sensorsd_flags != NO && -x /usr/sbin/sensorsd ]]; then
-	echo -n ' sensorsd';	/usr/sbin/sensorsd $sensorsd_flags
+	echo -n ' sensorsd';	sensorsd $sensorsd_flags
 fi
 
 if [[ $hotplugd_flags != NO && -x /usr/sbin/hotplugd ]]; then
-	echo -n ' hotplugd';	/usr/sbin/hotplugd $hotplugd_flags
+	echo -n ' hotplugd';	hotplugd $hotplugd_flags
 fi
 
 if [[ $watchdogd_flags != NO && -x /usr/sbin/watchdogd ]]; then
-	echo -n ' watchdogd';	/usr/sbin/watchdogd $watchdogd_flags
+	echo -n ' watchdogd';	watchdogd $watchdogd_flags
 fi
 
 echo -n ' cron';		cron
@@ -807,7 +780,7 @@ echo .
 date
 
 if [[ $wsmoused_flags != NO && -x /usr/sbin/wsmoused ]]; then
-	echo starting wsmoused...;	/usr/sbin/wsmoused $wsmoused_flags
+	echo starting wsmoused...;	wsmoused $wsmoused_flags
 fi
 
 # Alternatively, on some architectures, xdm may be started in /etc/ttys.
