Fix maintainer scripts and drop dh_installdirs

diff --git a/contrib/hosted/tg/deb/ca-bundle/debian/ca-bundle.postinst b/contrib/hosted/tg/deb/ca-bundle/debian/ca-bundle.postinst
--- a/contrib/hosted/tg/deb/ca-bundle/debian/ca-bundle.postinst
+++ b/contrib/hosted/tg/deb/ca-bundle/debian/ca-bundle.postinst
@@ -1,12 +1,32 @@
 #!/bin/sh
-# $MirOS: contrib/hosted/tg/deb/ca-bundle/debian/ca-bundle.postinst,v 1.2 2009/11/23 14:21:29 tg Exp $
+# $MirOS: contrib/hosted/tg/deb/jupp/debian/jupp.postinst,v 1.10 2011/09/06 20:07:39 tg Exp $
 
 set -e
+
+# This maintainer script can be called the following ways:
+#
+# * new-postinst "configure" [$most_recently_configured_version]
+# The package is unpacked; all dependencies are unpacked and, when there
+# are no circular dependencies, configured.
+#
+# * old-postinst "abort-upgrade" $new_version
+# * conflictors-postinst "abort-remove" "in-favour" $package
+#	$new_version
+# * postinst "abort-remove"
+# * deconfigureds-postinst "abort-deconfigure" "in-favour"
+#	$failed_install_package $fip_version ["removing"
+#	$conflicting_package $cp_version]
+# The package is unpacked; all dependencies are at least Half-Installed,
+# previously been configured, and not removed. In some error situations,
+# dependencies may not be even fully unpacked.
+#
+# * postinst "triggered" "${triggers[*]}"
+# For trigger-only calls, i.e. if "configure" is not called.
 
 case $1 in
 configure)
 	# on first installation
-	if [ -z "$2" ]; then
+	if test -z "$2"; then
 		rm -f /etc/ssl/certs/ca-certificates.crt* \
 		    /etc/ssl/certs/java/cacerts
 	fi
@@ -74,8 +94,11 @@ configure)
 abort-upgrade|abort-remove|abort-deconfigure)
 	;;
 
+triggered)
+	;;
+
 *)
-	echo "postinst called with unknown argument '$1'" >&2
+	echo >&2 "postinst called with unknown subcommand '$1'"
 	exit 1
 	;;
 esac
diff --git a/contrib/hosted/tg/deb/ca-bundle/debian/ca-bundle.postrm b/contrib/hosted/tg/deb/ca-bundle/debian/ca-bundle.postrm
--- a/contrib/hosted/tg/deb/ca-bundle/debian/ca-bundle.postrm
+++ b/contrib/hosted/tg/deb/ca-bundle/debian/ca-bundle.postrm
@@ -1,7 +1,26 @@
 #!/bin/sh
-# $MirOS$
+# $MirOS: contrib/hosted/tg/deb/jupp/debian/jupp.postrm,v 1.2 2011/09/06 20:07:39 tg Exp $
 
 set -e
+
+# This maintainer script can be called the following ways:
+#
+# * postrm "remove"
+# * postrm "purge"
+# * old-postrm "upgrade" $new_version
+# * disappearers-postrm "disappear" $overwriter $o_version
+# The package's files have been removed or replaced; only Essential pak-
+# kages may be available; skip gracefully actions requiring Depends.
+#
+# * new-postrm "failed-upgrade" $old_version
+# Called when 'old-postrm "upgrade"' fails; the new package is unpacked,
+# Essential packages and Pre-Depends are available; the latter have been
+# configured and never removed but may be Unpacked or Half-Configured.
+#
+# * new-postrm "abort-install" [$old_version]
+# * new-postrm "abort-upgrade" $old_version
+# Called when preinst fails; package is not unpacked. Essential packages
+# and (unpacked or Half-Configured) Pre-Depends are available.
 
 case $1 in
 remove)
@@ -9,15 +28,19 @@ remove)
 		test -f "$f" || rm -f "$f"
 	done
 	;;
+
 purge)
 	rm -rf /etc/ssl/certs/ca-certificates.crt* /etc/ssl/certs/java
-	[ -d /etc/ssl/certs ] && rmdir --ignore-fail-on-non-empty /etc/ssl/certs
-	[ -d /etc/ssl ] && rmdir --ignore-fail-on-non-empty /etc/ssl
+	test -d /etc/ssl/certs && \
+	    rmdir --ignore-fail-on-non-empty /etc/ssl/certs
+	test -d /etc/ssl && rmdir --ignore-fail-on-non-empty /etc/ssl
 	;;
-upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+
+upgrade|disappear|failed-upgrade|abort-install|abort-upgrade)
 	;;
+
 *)
-	echo "postrm called with unknown argument '$1'" >&2
+	echo >&2 "postrm called with unknown subcommand '$1'"
 	exit 1
 	;;
 esac
diff --git a/contrib/hosted/tg/deb/ca-bundle/debian/ca-bundle.prerm b/contrib/hosted/tg/deb/ca-bundle/debian/ca-bundle.prerm
--- a/contrib/hosted/tg/deb/ca-bundle/debian/ca-bundle.prerm
+++ b/contrib/hosted/tg/deb/ca-bundle/debian/ca-bundle.prerm
@@ -1,7 +1,36 @@
 #!/bin/sh
-# $MirOS: contrib/hosted/tg/deb/ca-bundle/debian/ca-bundle.postrm,v 1.2 2009/11/23 14:21:29 tg Exp $
+# $MirOS: contrib/hosted/tg/deb/jupp/debian/jupp.prerm,v 1.4 2011/09/06 20:07:39 tg Exp $
 
 set -e
+
+# This maintainer script can be called the following ways:
+#
+# * prerm "remove"
+# * old-prerm "upgrade" $new_version
+# * conflictors-prerm "remove" "in-favour" $package $new_version
+# * deconfigureds-prerm "deconfigure" "in-favour"
+#	$package_being_installed $pbi_version ["removing"
+#	$conflicting_package $cp_version]
+# The package and dependencies are at least Half-Installed; dependencies
+# have previously been configured and not removed.
+#
+# * new-prerm "failed-upgrade" $old_version
+# Called when 'old-prerm "upgrade"' fails; new package not unpacked, all
+# other constraints the same as above.
+
+case $1 in
+remove|deconfigure)
+	;;
+
+upgrade|failed-upgrade)
+	;;
+
+*)
+	echo >&2 "prerm called with unknown subcommand '$1'"
+	exit 1
+	;;
+esac
+
 
 nukeifeq() {
 	if cmp -s "$1" "$2" 2>/dev/null; then
@@ -12,22 +41,11 @@ nukeifeq() {
 crtdir=/etc/ssl/certs
 datadir=/usr/share/ca-bundle
 
-case $1 in
-purge|upgrade|deconfigure)
-	# remove files if generated by us, so that next package version
-	# can install their own, differing ones
-	nukeifeq $crtdir/ca-certificates.crt $datadir/ca-certificates.crt
-	nukeifeq $crtdir/java/cacerts $datadir/keystore.jks
-	;;
+# remove files if generated by us, so that next package version
+# can install their own, differing ones
+nukeifeq $crtdir/ca-certificates.crt $datadir/ca-certificates.crt
+nukeifeq $crtdir/java/cacerts $datadir/keystore.jks
 
-remove|failed-upgrade)
-	;;
-
-*)
-	echo "prerm called with unknown argument '$1'" >&2
-	exit 1
-	;;
-esac
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
