merge

diff --git a/contrib/gnu/aux/move-if-change b/contrib/gnu/aux/move-if-change
--- a/contrib/gnu/aux/move-if-change
+++ b/contrib/gnu/aux/move-if-change
@@ -1,57 +1,24 @@
-#!/usr/bin/env mksh
-# $MirOS: contrib/gnu/aux/move-if-change,v 1.6 2008/05/02 23:06:01 tg Exp $
+#!/bin/sh
+# $MirOS$
 #-
-# Copyright (c) 2004, 2008
-#	Thorsten Glaser <tg@mirbsd.de>
-#
-# Provided that these terms and disclaimer and all copyright notices
-# are retained or reproduced in an accompanying document, permission
-# is granted to deal in this work without restriction, including un-
-# limited rights to use, publicly perform, distribute, sell, modify,
-# merge, give away, or sublicence.
-#
-# This work is provided "AS IS" and WITHOUT WARRANTY of any kind, to
-# the utmost extent permitted by applicable law, neither express nor
-# implied; without malicious intent or gross negligence. In no event
-# may a licensor, author or contributor be held liable for indirect,
-# direct, other damage, loss, or other issues arising in any way out
-# of dealing in the work, even if advised of the possibility of such
-# damage or existence of a defect, except proven that it results out
-# of said person's immediate fault when using the work as intended.
-#-
-# Compare a to b; if b is newer, replace b with a
+# Like mv $1 $2, but if the files are the same, just delete $1.
+# Status is zero if successful, nonzero otherwise.
 
-: ${MKSH:=$(whence -p mksh)}
-copy=
+usage="$0: usage: $0 SOURCE DEST"
 
-if [[ $1 = -c ]]; then
-	copy=-c
-	shift
+case $# in
+2) ;;
+*) echo "$usage" >&2; exit 1;;
+esac
+
+for arg in "$1" "$2"; do
+  case $arg in
+   -*) echo "$usage" >&2; exit 1;;
+  esac
+done
+
+if test -r "$2" && cmp -s "$1" "$2"; then
+  exec rm -f "$1"
+else
+  exec mv -f "$1" "$2"
 fi
-
-if [ $# -gt 2 ]; then
-	set -A parms -- "$@"
-	let i=${#parms[*]}-1
-	target=${parms[i]}
-	unset parms[i]
-
-	if [[ ! -d $target ]]; then
-		print -u2 "$target not a directory"
-		exit 1
-	fi
-	set -e
-	for src in "${parms[@]}"; do
-		$MKSH "$0" $copy "$src" "$target"
-	done
-	set +e
-	exit 0
-fi
-
-[[ -r $2 ]] && if cmp "$1" "$2" >/dev/null 2>&1; then
-	echo "$2 is unchanged"
-	[[ -n $copy ]] || rm -f "$1"
-	exit 0
-fi
-
-[[ -z $copy ]] || exec cp -f "$1" "$2"
-exec mv -f "$1" "$2"
