Update firesomething to 1.5.0.3-0.
Our build is "unofficial" for trademark reasons and thus calls itself
"Deer Park" (the code name). The executable is called "firesomething", as
usual.

This probably needs -current, but it runs on my own -stable too (I have
rebuilt ld and src/lib from source). Don't even bother with it on #7.

diff --git a/ports/www/firesomething/patches/patch-browser_app_mozilla_in b/ports/www/firesomething/patches/patch-browser_app_mozilla_in
--- a/ports/www/firesomething/patches/patch-browser_app_mozilla_in
+++ b/ports/www/firesomething/patches/patch-browser_app_mozilla_in
@@ -1,24 +1,32 @@
-$OpenBSD: patch-browser_app_mozilla_in,v 1.1.1.1 2004/02/15 19:37:25 wilfried Exp $
---- browser/app/mozilla.in.orig	2003-07-26 09:51:05.000000000 +0200
-+++ browser/app/mozilla.in	2004-01-19 15:19:46.000000000 +0100
-@@ -33,6 +33,7 @@
+$OpenBSD: patch-browser_app_mozilla_in,v 1.4 2005/10/13 04:32:41 bernd Exp $
+--- browser/app/mozilla.in.orig	Tue Sep 20 23:12:41 2005
++++ browser/app/mozilla.in	Fri Dec  9 21:06:47 2005
+@@ -93,6 +93,7 @@ moz_pis_startstop_scripts()
  #set -x
  
  moz_libdir=%MOZAPPDIR%
-+MOZ_PLUGIN_PATH=_LOCALBASE_/lib/mozilla-plugins
++MOZ_PLUGIN_PATH=/usr/mpkg/lib/mozilla-plugins
  MRE_HOME=%MREDIR%
  
  # Use run-mozilla.sh in the current dir if it exists
-@@ -106,7 +107,11 @@ do
+@@ -130,6 +131,7 @@ if [ $found = 0 ]; then
+   # Check default compile-time libdir
+   if [ -x "$moz_libdir/run-mozilla.sh" ]; then
+     dist_bin="$moz_libdir"
++    run_moz="$dist_bin/run-mozilla.sh"
+   else 
+     echo "Cannot find mozilla runtime directory. Exiting."
+     exit 1
+@@ -171,7 +173,11 @@ do
    esac
  done
  
 -export MRE_HOME
-+if [ `_X11BASE_/bin/fc-list | wc -l` -eq 0 ]
++if [ `/usr/X11R6/bin/fc-list | wc -l` -eq 0 ]
 +then export GDK_USE_XFT=0
 +fi
 +
 +export MOZ_PLUGIN_PATH MRE_HOME
- eval "set -- $moreargs"
- if [ $debugging = 1 ]
- then
+ 
+ ## Start addon scripts
+ moz_pis_startstop_scripts "start"
