sync

diff --git a/ports/infrastructure/db/install-sh b/ports/infrastructure/db/install-sh
--- a/ports/infrastructure/db/install-sh
+++ b/ports/infrastructure/db/install-sh
@@ -1,6 +1,6 @@
-#!/bin/mksh
-# $MirOS: contrib/gnu/aux/install-sh,v 1.6 2005/05/26 21:21:18 tg Exp $
-# _MirOS: contrib/gnu/aux/install-sh,v 1.6 2005/05/26 21:21:18 tg Exp $
+#!/bin/sh
+# $MirOS: contrib/gnu/aux/install-sh,v 1.8 2005/09/13 10:42:27 tg Exp $
+# _MirOS: contrib/gnu/aux/install-sh,v 1.8 2005/09/13 10:42:27 tg Exp $
 #-
 # Copyright (c) 2004, 2005
 #	Thorsten "mirabile" Glaser <tg@66h.42h.de>
@@ -24,6 +24,31 @@
 # rect or other, however caused, arising in any way out of the usage
 # of this work, even if advised of the possibility of such damage.
 
+if test x"$KSH_VERSION" = x; then
+	if test x"$MKSH" = x; then
+		MKSH=/bin/mksh
+	fi
+	if test -f $MKSH; then
+		SHELL=$MKSH
+		export SHELL
+		case $# in
+		0)	exec $MKSH "$0" ;;
+		*)	exec $MKSH "$0" "$@" ;;
+		esac
+	fi
+	# Only here if spawning mksh failed
+	test x"$BASH_VERSION" = x && for i in {,/usr{,/local},/sw}/bin; do
+		if test -f $i/bash; then
+			SHELL=$i/bash
+			export SHELL
+			case $# in
+			0)	exec $i/bash "$0" ;;
+			*)	exec $i/bash "$0" "$@" ;;
+			esac
+		fi
+	done
+fi
+
 # XXX how to check for ksh88?
 if [ -n "$BASH_VERSION" ]; then
 	shopt -s extglob
@@ -36,19 +61,21 @@ elif [ -n "$SH_VERSION" ]; then
 		;;
 	esac
 elif [[ -n $KSH_VERSION ]]; then
-	set +o sh +o posix
 	p=print
 fi
 
 if [ -z "$p" ]; then
-	echo "Shell not supported; go to http://wiki.mirbsd.de/MirbsdKsh"
+	echo "Shell not supported; go to http://mirbsd.mirsolutions.de/?mksh"
 	exit 1
 fi
 
 allargs="$*"
 
+installprog=/usr/bin/install
+test -x /usr/ucb/install && installprog=/usr/ucb/install
+
 if [[ $allargs != *@(-t=|-b=)* && -z $SFUDIR ]]; then
-	exec /usr/bin/install "$@"
+	exec $installprog "$@"
 fi
 
 args=
@@ -116,8 +143,8 @@ while (( i < dstoff )); do
 		[[ -n $dsttmp ]] && dstfile="$dsttmp"
 	fi
 
-	/usr/bin/install $args "$src" "${dstdir}/${dstfile}" || exit 1
+	$installprog $args "$src" "${dstdir}/${dstfile}" || exit 1
 
-	let i+=1
+	let i++
 done
 exit 0
