time to update this as well

diff --git a/src/gnu/share/install-reloc b/src/gnu/share/install-reloc
--- a/src/gnu/share/install-reloc
+++ b/src/gnu/share/install-reloc
@@ -1,14 +1,15 @@
 #!/bin/sh
-# $MirOS: contrib/gnu/gettext/config/install-reloc,v 1.2 2005/02/05 02:28:21 tg Exp $
-# _MirOS: contrib/gnu/gettext/config/install-reloc,v 1.2 2005/02/05 02:28:21 tg Exp $
+# $MirOS: contrib/gnu/aux/install-reloc,v 1.3 2008/05/03 19:34:34 tg Exp $
+# $miros: contrib/gnu/aux/install-reloc,v 1.3 2008/05/03 19:34:34 tg Exp $
+#-
 # install-reloc - install a program including a relocating wrapper
-# Copyright (C) 2003 Free Software Foundation, Inc.
+# Copyright (C) 2003, 2005-2007 Free Software Foundation, Inc.
 # Written by Bruno Haible <bruno@clisp.org>, 2003.
 #
-# This program is free software; you can redistribute it and/or modify
+# This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2, or (at your option)
-# any later version.
+# the Free Software Foundation; either version 3 of the License, or
+# (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
@@ -16,21 +17,26 @@
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
-# along with this program; if not, write to the Free Software
-# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 # Usage:
-#   install-reloc library_path_var library_path_value prefix compile_command srcdir config_h_dir install_command... destprog
+#   install-reloc library_path_var library_path_value prefix destdir \
+#                 compile_command srcdir config_h_dir exeext \
+#                 install_command... destprog
 # where
 #   - library_path_var is the platform dependent runtime library path variable
 #   - library_path_value is a colon separated list of directories that contain
 #     the libraries at installation time (use this instead of -rpath)
 #   - prefix is the base directory at installation time
+#   - destdir is a string that is prepended to all file names at installation
+#     time; it is already prepended to destprog but not to library_path_value
+#     and prefix
 #   - compile_command is a C compiler compilation and linking command
 #   - srcdir is the directory where to find relocwrapper.c and its dependencies
 #   - builddir is the directory where to find built dependencies (namely,
 #     alloca.h and stdbool.h)
 #   - config_h_dir is the directory where to find config.h
+#   - exeext is platform dependent suffix of executables
 #   - install-command is the install command line, excluding the final destprog
 #   - destprog is the destination program name
 # install-reloc renames destprog to destprog.bin and installs a relocating
@@ -43,22 +49,25 @@ if test $# -eq 2; then
   library_path_var=$RELOC_LIBRARY_PATH_VAR
   library_path_value=$RELOC_LIBRARY_PATH_VALUE
   prefix=$RELOC_PREFIX
+  destdir=$RELOC_DESTDIR
   compile_command=$RELOC_COMPILE_COMMAND
   srcdir=$RELOC_SRCDIR
   builddir=$RELOC_BUILDDIR
   config_h_dir=$RELOC_CONFIG_H_DIR
+  exeext=$RELOC_EXEEXT
   install_prog=$RELOC_INSTALL_PROG # including the "-c" option
 else
-  if test $# -ge 9; then
+  if test $# -ge 10; then
     # Get fixed position arguments.
     library_path_var=$1
     library_path_value=$2
     prefix=$3
-    compile_command=$4
-    srcdir=$5
-    builddir=$6
-    config_h_dir=$7
-    install_prog=$8 # maybe not including the "-c" option
+    destdir=$4
+    compile_command=$5
+    srcdir=$6
+    builddir=$7
+    config_h_dir=$8
+    exeext=$9
     shift
     shift
     shift
@@ -66,9 +75,14 @@ else
     shift
     shift
     shift
+    shift
+    shift
+    install_prog=$1 # maybe not including the "-c" option
     shift
   else
-    echo "Usage: $0 library_path_var library_path_value prefix compile_command srcdir builddir config_h_dir install_command... destprog" 1>&2
+    echo "Usage: $0 library_path_var library_path_value prefix destdir" \
+         "compile_command srcdir builddir config_h_dir exeext" \
+         "install_command... destprog" 1>&2
     exit 1
   fi
 fi
@@ -79,6 +93,12 @@ for arg
 do
   destprog=$arg
 done
+# Remove trailing $exeext, if present.
+if test -n "$exeext"; then
+  sed_quote='s,\.,\\.,g'
+  sed_remove_exeext='s|'`echo "$exeext" | sed -e "$sed_quote"`'$||'
+  destprog=`echo "$destprog" | sed -e "$sed_remove_exeext"`
+fi
 
 # Outputs a command and runs it.
 func_verbose ()
@@ -110,12 +130,54 @@ IFS="$save_IFS"
 # wrapper.
 test -n "$libdirs" || exit 0
 
-# Compile wrapper.
+# Determine installdir from destprog, removing a leading destdir if present.
 installdir=`echo "$destprog" | sed -e 's,/[^/]*$,,'`
-func_verbose $compile_command -I"$builddir" -I"$srcdir" -I"$config_h_dir" -DHAVE_CONFIG_H -DNO_XMALLOC -D"INSTALLPREFIX=\"$prefix\"" -D"INSTALLDIR=\"$installdir\"" -D"LIBPATHVAR=\"$library_path_var\"" -D"LIBDIRS=$libdirs" "$srcdir"/relocwrapper.c "$srcdir"/progname.c "$srcdir"/progreloc.c "$srcdir"/xreadlink.c "$srcdir"/readlink.c "$srcdir"/canonicalize.c "$srcdir"/allocsa.c "$srcdir"/relocatable.c "$srcdir"/setenv.c "$srcdir"/strerror.c -o $destprog.wrapper || exit $?
+if test -n "$destdir"; then
+  sed_quote='s,\([|.\*^$[]\),\\\1,g'
+  sed_remove_destdir='s|^'`echo "$destdir" | sed -e "$sed_quote"`'||'
+  installdir=`echo "$installdir" | sed -e "$sed_remove_destdir"`
+fi
+
+# Compile wrapper.
+func_verbose $compile_command \
+             -I"$builddir" -I"$srcdir" -I"$config_h_dir" \
+             -DHAVE_CONFIG_H -DIN_RELOCWRAPPER -DNO_XMALLOC \
+             -D"INSTALLPREFIX=\"$prefix\"" -D"INSTALLDIR=\"$installdir\"" \
+             -D"LIBPATHVAR=\"$library_path_var\"" -D"LIBDIRS=$libdirs" \
+             -D"EXEEXT=\"$exeext\"" \
+             "$srcdir"/relocwrapper.c \
+             "$srcdir"/progname.c \
+             "$srcdir"/progreloc.c \
+             "$srcdir"/areadlink.c \
+             "$srcdir"/readlink.c \
+             "$srcdir"/canonicalize-lgpl.c \
+             "$srcdir"/malloca.c \
+             "$srcdir"/relocatable.c \
+             "$srcdir"/setenv.c \
+             "$srcdir"/strerror.c \
+             "$srcdir"/c-ctype.c \
+             -o "$destprog.wrapper$exeext"
+rc=$?
+# Clean up object files left over in the current directory by the native C
+# compilers on Solaris, HP-UX, OSF/1, IRIX.
+rm -f relocwrapper.o \
+      progname.o \
+      progreloc.o \
+      xreadlink.o \
+      areadlink.o \
+      canonicalize-lgpl.o \
+      malloca.o \
+      relocatable.o \
+      setenv.o \
+      strerror.o \
+      c-ctype.o
+test $rc = 0 || exit $?
 
 # Rename $destprog.wrapper -> $destprog -> $destprog.bin.
-ln -f $destprog $destprog.bin || exit 1
-mv $destprog.wrapper $destprog || exit 1
+ln -f "$destprog$exeext" "$destprog.bin$exeext" \
+  || { rm -f "$destprog.bin$exeext" \
+       && cp -p "$destprog$exeext" "$destprog.bin$exeext"; } \
+  || exit 1
+mv "$destprog.wrapper$exeext" "$destprog$exeext" || exit 1
 
 exit 0
