let this exit 1 if AUTO*_VERSION is not set and add a manual page

diff --git a/ports/devel/metaauto/files/meta.in b/ports/devel/metaauto/files/meta.in
--- a/ports/devel/metaauto/files/meta.in
+++ b/ports/devel/metaauto/files/meta.in
@@ -1,35 +1,14 @@
 #!/bin/sh
-# $MirOS$
-# $OpenBSD: meta.in,v 1.2 2004/04/12 10:35:27 matthieu Exp $
-#
-# Copyright (c) 2003 Marc Espie.
-#
-# Redistribution and use in source and binary forms, with or without
-# modification, are permitted provided that the following conditions
-# are met:
-# 1. Redistributions of source code must retain the above copyright
-#    notice, this list of conditions and the following disclaimer.
-# 2. Redistributions in binary form must reproduce the above copyright
-#    notice, this list of conditions and the following disclaimer in the
-#    documentation and/or other materials provided with the distribution.
-#
-# THIS SOFTWARE IS PROVIDED BY THE OPENBSD PROJECT AND CONTRIBUTORS
-# ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-# A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OPENBSD
-# PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+# $MirOS: ports/devel/metaauto/files/meta.in,v 1.1.7.1 2005/03/18 15:44:58 tg Exp $
+#-
+# Idea from Marc Espie.
 
-case "x$AUTOTOOLS_VERSION" in
-x)	# figure out manually what to do
-	echo "Provide an AUTOTOOLS_VERSION environment variable, please"
-	;;
-x*)
-	exec @LOCALBASE@/bin/@SCRIPT@-$AUTOTOOLS_VERSION "$@"
-	;;
-esac
+if test -n "$AUTOTOOLS_VERSION"; then
+	test -x @LOCALBASEQ@/bin/@SCRIPT@-"$AUTOTOOLS_VERSION" && \
+	    exec @LOCALBASEQ@/bin/@SCRIPT@-"$AUTOTOOLS_VERSION" "$@"
+	echo >&2 "Could not find @SCRIPT@-$AUTOTOOLS_VERSION"
+	exit 255
+fi
+
+echo >&2 "Provide an AUTOTOOLS_VERSION environment variable, please"
+test x"$AUTOTOOLS_NOTSET_OK" = x"1"
